services:
  mariadb:
    container_name: mariadb_mealmaster
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Wasserkopf45
      MYSQL_DATABASE: mealmaster