version: '3.8'
services:
  app:
    container_name: app_mealmaster_prod
    build: .
    restart: always
    ports:
      - "80:8080"
    networks:
      - app-network
  mariadb:
    container_name: mariadb_mealmaster_prod
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 647e5c285aa06f6a6419d2dcf93ca536
      MYSQL_DATABASE: mealmaster
      MYSQL_USER: mealmaster_user
      MYSQL_PASSWORD: d4bc1e78e053c6c2d0419bd742b41adc
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb_mealmaster
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
